name: Java CI with Maven

on:
  push:
    branches: [ main ]

jobs:
  
  Build:
    name: Selenium Test Job
    runs-on: windows-latest
    env:
      SELENIUM_DRIVER: 'RemoteWebDriver'
    
    steps:
      - run: echo "This is running inside a ${{ runner.os }} serve in GitHub"
      - run: echo "The code is being triggered by ${{ github.repository_owner }}"
      - name: checkout source code
        uses: actions/checkout@v2.4.0
      - run: echo "This repo is ${{ github.repository }} .."
      - name: Run a inline script
        run: |
          mkdir another_tripadvisor
          ls -l
        shell: bash
      - name: Run Selenium Test
        if: ${{ env.SELENIUM_DRIVER == 'RemoteWebDriver' }}
        run: echo "Running test in Selenium setup"
      
      
  Build2:
    name: Selenium Test Job 2
    runs-on: ubuntu-latest
    
    steps:
      - run: echo "This is from second job"
    needs: Build
    if: ${{ always() }}

